sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: sky-take-out-yjp
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid:  wxc8823c2ffbe8df4b
    secret: 036b225e68f20b7a9fa0bb7e8a9f7010